# Generated by Django 3.0.3 on 2021-06-04 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genedata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hello',
            name='person',
            field=models.CharField(default='unknown', max_length=200),
        ),
    ]
