# Generated by Django 3.0.3 on 2021-06-12 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genedata', '0003_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='Protein',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protein_id', models.CharField(max_length=200)),
                ('sequence', models.CharField(blank=True, max_length=40000)),
            ],
        ),
    ]
