# Generated by Django 3.0.3 on 2021-06-12 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genedata', '0004_protein'),
    ]

    operations = [
        migrations.AddField(
            model_name='protein',
            name='length',
            field=models.IntegerField(default=50),
        ),
    ]
