# Generated by Django 3.0.3 on 2021-06-12 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genedata', '0005_protein_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protein',
            name='length',
            field=models.IntegerField(default=50, max_length=10),
        ),
    ]
