# Generated by Django 3.0.3 on 2021-06-12 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genedata', '0006_auto_20210612_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protein',
            name='length',
            field=models.IntegerField(default=50),
        ),
    ]
