# Generated by Django 3.0.3 on 2021-06-13 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genedata', '0007_auto_20210612_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protein',
            name='length',
            field=models.IntegerField(default=0),
        ),
    ]
