# Generated by Django 3.0.3 on 2021-06-13 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genedata', '0008_auto_20210613_0941'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organism',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxa_id', models.IntegerField(default=0)),
                ('clade', models.CharField(max_length=1)),
                ('genus', models.CharField(max_length=200)),
            ],
        ),
    ]
