# Generated by Django 3.0.3 on 2021-06-13 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genedata', '0009_organism'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protein_seq_id', models.IntegerField(default=1)),
                ('organism_id', models.IntegerField(default=2)),
                ('pfam_id', models.IntegerField(default=3)),
                ('start', models.IntegerField()),
                ('stop', models.IntegerField()),
            ],
        ),
    ]
