# Generated by Django 3.0.3 on 2021-06-13 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genedata', '0010_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='organism_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.SET_DEFAULT, to='genedata.Organism'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='pfam_id',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.SET_DEFAULT, to='genedata.Domain'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='protein_seq_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='genedata.Protein'),
        ),
    ]
