# Generated by Django 3.0.3 on 2021-06-14 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genedata', '0012_auto_20210613_1920'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='stop',
            new_name='end',
        ),
    ]
