# Generated by Django 3.0.3 on 2021-06-14 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genedata', '0014_auto_20210614_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='organism_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='genedata.Organism'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='pfam_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='genedata.Domain'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='protein_seq_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='genedata.Protein'),
        ),
    ]
