# Generated by Django 3.0.3 on 2021-06-14 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genedata', '0015_auto_20210614_1844'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hello',
        ),
    ]
