# Generated by Django 3.0.3 on 2021-06-17 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genedata', '0016_delete_hello'),
    ]

    operations = [
        migrations.AddField(
            model_name='protein',
            name='taxa_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='genedata.Organism'),
        ),
    ]
