# Generated by Django 3.0.3 on 2021-06-17 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genedata', '0017_protein_taxa_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='organism_id',
        ),
    ]
