# Generated by Django 3.0.3 on 2021-06-17 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genedata', '0018_remove_assignment_organism_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='protein_seq_id',
            new_name='protein_id',
        ),
    ]
