# Generated by Django 3.0.3 on 2021-06-17 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genedata', '0019_auto_20210617_1546'),
    ]

    operations = [
        migrations.RenameField(
            model_name='protein',
            old_name='taxa_id',
            new_name='taxonomy',
        ),
    ]
