# Generated by Django 3.0.3 on 2021-06-17 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genedata', '0020_auto_20210617_1624'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='end',
            new_name='stop',
        ),
    ]
