# Generated by Django 3.0.3 on 2021-06-17 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genedata', '0021_auto_20210617_1631'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='protein_id',
            new_name='protein',
        ),
    ]
