# Generated by Django 3.0.3 on 2021-06-17 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genedata', '0022_auto_20210617_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='organism',
            name='species',
            field=models.CharField(default='EMPTY', max_length=200),
        ),
    ]
